# roles/traefik/tasks/main.yaml
- name: Create traefik config dir
  file:
    path: "{{ traefik_config_dir }}"
    state: directory
    mode: '0755'

- name: Write static config
  copy:
    dest: "{{ traefik_config_dir }}/traefik.yml"
    content: |
      entryPoints:
        web:
          address: ":80"
          redirections:
            entrypoint:
              to: websecure
              scheme: https
        websecure:
          address: ":443"
        web-internal:
          address: ":8080"
      api:
        dashboard: true
        insecure: true
      providers:
        docker:
          endpoint: "unix:///var/run/podman.sock"
          exposedByDefault: false
          network: proxy
      certificatesResolvers:
        letsencrypt:
          acme:
            email: "{{ domain_email }}"
            storage: "/etc/traefik/acme.json"
            httpChallenge:
              entryPoint: web

- name: Create Traefik container
  container.podman.podmain_container:
    name: {{ traefik_container_name }}
    image: {{ traefik_container_image }}
    rm: true
    state: created
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`localhost`)"
      traefik.http.routers.traefik.entrypoints: "web-internal"
      traefik.http.routers.traefik.service: "api@internal"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/podman/podman.sock:/var/run/podman.sock:ro,z
      - "{{ traefik_config_dir }}:/etc/traefik:rw:z"
      - "/etc/letsencrypt:/etc/letsencrypt:rw:z"
    network: proxy
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    restart_policy: "always"

- name: Generate systemd unit file for Traefik container
  containers.podman.podman_generate_systemd:
    name: {{ traefik_container_name }}
    new: true
    no_header: true
    dest: /etc/systemd/system

- name: Enable and start Traefik service
  ansible.buildin.systemd:
    name: "container-{{ traefik_container_name }}"
    enabled: true
    state: started
    daemon_reload: true